version: '3'
services:
    nginx_katerfink:
        container_name: nginx_katerfink
        build: .
        restart: always
        volumes:
            - ./html:/usr/share/nginx/html
        ports:
            - "80:80"
